# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe85b9b9125d6931f5f03a29d2949f49c38d0c70f40ce5e47103aff52cae185ec143b462828c4bea9340ac1e0dd21e346d026e480336e85dd3803def9460178

test:
  secret_key_base: efc8fc4c24dc2917cbc32a4d6247fdb183a13d31cb8f1b86845bb2105fad9e45353a373e491f29ab20066664d0d9993bbbb34e2e8a125c3b5eadac55f127c04a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
